name: Run CI

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
    - uses: actions/checkout@v4

    - uses: wntrblm/nox@main

    - id: set-matrix
      shell: bash
      run: echo session=$(nox --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT
      working-directory: ${{ inputs.package-directory }}

  checks:
    name: Session ${{ matrix.session }}
    needs: [generate-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-jobs.outputs.session) }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up nox
      uses: wntrblm/nox@main

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - run: nox -s "${{ matrix.session }}"
      working-directory: ${{ inputs.package-directory }}

  coverage:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up nox
        uses: wntrblm/nox@main

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Make coverage report
        run: nox -s coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            use_oidc: true
            token: ${{ secrets.CODECOV_TOKEN }}